spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/eduzone?useSSL=false&serverTimezone=UTC
    username: root
    password: zxczxc123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [email, profile]
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

jwt:
  secret: your_very_secret_key_here
  expiration: 86400000  # 1 day in ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

app:
  jwt:
    secret: "your-very-very-long-secret-key-at-least-32-chars"
    expiration-ms: 7200000
  google:
    client-id: "YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"

server:
  port: 8081
